---
# Last edit 23 July 2024 - david.nix@hci.utah.edu
# Configuration for the bulk RnaAlignQC workflow, keeping it simple, just hardcoding for redwood
# Human latest

genomeBuild: Hg38

# Illumina Nextera
adapterR1: CTGTCTCTTATACACATCT
adapterR2: CTGTCTCTTATACACATCT

# OD for removing duplicates with clumpify: 50 to 100 for NovaSeqX, 12000 for NovaSeq6000, 40 for HiSeq 2500
opticalDistance: 100
mappingQuality: 13
baseQuality: 13

# root must end in /
root: /uufs/chpc.utah.edu/common/PE/hci-bioinformatics1/atlatl/data/
chrom: Human/GRCh38/chrom.sizes
fqsConfig: FastQ_Screen_Genomes/redwood_fastq_screen.conf
multiQCConfig: MultiQC/bulkRnaSeq_multiqc_config.yaml
analysisRegions: Human/Hg38/TNRunner/mergedNimV1IdtV1-2TwistV2Pad175bp8March2023.bed.gz

# use 100bp for reads at and over 100bp, use the star50 for short reads
starIndex: Human/GRCh38/release112/star100
gtf: Human/GRCh38/release112/Homo_sapiens.GRCh38.112.gtf
refFlat: Human/GRCh38/release112/Homo_sapiens.GRCh38.112.refflat
riboIntervals: Human/GRCh38/release112/Homo_sapiens.GRCh38.112.rRNA.interval
rsemIndex: Human/GRCh38/release112/rsem/RSEM
fastaIndex: Human/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa

# Must match chr usage (chr1 or just 1) of the input cram for fastq conversion
cramIndex: Human/Hg38/hg38.with_alt.fa

# Strandedness, set all to the same
rsemStrand: reverse # 'none', 'forward', and 'reverse' (default)
fcStrand: 2 # 0 (unstranded), 1 (stranded, Tempus) and 2 (reversely stranded, default)
crsStrand: SECOND_READ_TRANSCRIPTION_STRAND # NONE, FIRST_READ_TRANSCRIPTION_STRAND, SECOND_READ_TRANSCRIPTION_STRAND (default)



