---
# Last edit 10 June 2025 - david.nix@hci.utah.edu
# Configuration for the AutoAnalysis DnaAlignQC workflow, keeping it simple, just hardcoding for redwood
# NOTE! The read coverage statistics are only valid for WGS (including chIPSeq like experiments) or exome capture.
#    Small panel captures require reanalysis with a capture matched set of bed files.
#    Likewise UMI consensus deduplicate collapsing requires reanalysis.

# Mouse latest
genomeBuild: GRCm39

# Illumina TruSeq universal adapters
adapters: /BioApps/Trimmomatic/0.39/adapters/TruSeq3-PE.fa

# Set this to 2500 for NovaSeq/NextSeq datasets, set it to 100 for HiSeq/MiSeq datasets, set to 0 for fastq from SRA to disable
opticalDistance: 2500

mappingQuality: 13
baseQuality: 13

# Used to create a bed file of regions that pass this minimum unique observations threshold
passingReadDepth: 12

# Atlatl data bundle must end in /
atlatl: /uufs/chpc.utah.edu/common/PE/hci-bioinformatics1/atlatl/data/
fqsConfig: FastQ_Screen_Genomes/redwood_fastq_screen.conf

# TNRunner data bundle, must end in /
tnRunner: /uufs/chpc.utah.edu/common/PE/hci-bioinformatics1/TNRunner/
fastaIndex: Indexes/Mouse/GRCm39/Mus_musculus.GRCm39.dna.primary_assembly.fa
uniObRCRegions: Bed/Mouse/GRCm39_TwstExonNoRepMskStdChrs.bed.gz


